# Generated by Django 5.2.13 on 2026-05-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesettings_workday_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='class_of_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC')], max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Line manager or reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_government',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification_obtained',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_of_graduation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
