# Generated by Django 5.2.13 on 2026-05-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employeecertification_employeeeducation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick Day'), ('authorized_absence', 'Authorized Absence'), ('training', 'Training'), ('remote', 'Remote Work'), ('half_day', 'Half Day')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to='attendance.employee')),
            ],
            options={
                'ordering': ['-start_date', '-end_date', 'employee__first_name'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_c206dc_idx'), models.Index(fields=['employee', 'start_date'], name='attendance__employe_1f5c0b_idx')],
            },
        ),
    ]
