# Generated by Django 5.2.13 on 2026-05-27 18:30

from django.db import migrations, models


def seed_attendance_exception_types(apps, schema_editor):
    AttendanceExceptionType = apps.get_model('attendance', 'AttendanceExceptionType')
    defaults = [
        ('authorized_absence', 'Authorized Absence', 'Approved time away from work.', 'info'),
        ('compassionate_leave', 'Compassionate Leave', 'Approved leave for bereavement or urgent family matters.', 'secondary'),
        ('half_day', 'Half Day', 'Approved half-day exception.', 'warning'),
        ('leave', 'Leave', 'Approved leave day or leave period.', 'success'),
        ('maternity_leave', 'Maternity Leave', 'Approved maternity leave period.', 'danger'),
        ('paternity_leave', 'Paternity Leave', 'Approved paternity leave period.', 'primary'),
        ('public_holiday', 'Public Holiday', 'Company-recognized public holiday.', 'info'),
        ('remote', 'Remote Work', 'Approved remote work day.', 'primary'),
        ('sick', 'Sick Day', 'Employee is unavailable due to illness.', 'danger'),
        ('study_leave', 'Study Leave', 'Approved leave for exams, study, or professional learning.', 'warning'),
        ('training', 'Training', 'Employee is away for training or development.', 'info'),
    ]
    for code, name, description, color in defaults:
        AttendanceExceptionType.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'description': description,
                'color': color,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceExceptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class, e.g. primary, warning, info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='attendanceexception',
            name='exception_type',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(seed_attendance_exception_types, migrations.RunPython.noop),
    ]
