# Generated by Django 5.2.13 on 2026-05-28 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_leave_types(apps, schema_editor):
    Organization = apps.get_model('attendance', 'Organization')
    LeaveType = apps.get_model('attendance', 'LeaveType')

    leave_types = [
        ('annual_leave', 'Annual Leave', 21, 'success', False, True),
        ('sick_leave', 'Sick Leave', 10, 'danger', True, True),
        ('study_leave', 'Study Leave', 5, 'warning', False, True),
        ('compassionate_leave', 'Compassionate Leave', 5, 'secondary', False, True),
        ('maternity_leave', 'Maternity Leave', 90, 'danger', True, True),
        ('paternity_leave', 'Paternity Leave', 14, 'primary', False, True),
        ('unpaid_leave', 'Unpaid Leave', 0, 'secondary', False, False),
    ]

    for organization in Organization.objects.all():
        for code, name, entitlement, color, requires_attachment, is_paid in leave_types:
            LeaveType.objects.get_or_create(
                organization=organization,
                code=code,
                defaults={
                    'name': name,
                    'annual_entitlement_days': entitlement,
                    'color': color,
                    'requires_attachment': requires_attachment,
                    'is_paid': is_paid,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_organization_multitenancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('annual_entitlement_days', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='success', help_text='Bootstrap color class, e.g. success, warning, info', max_length=20)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='attendance.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_part', models.CharField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full_day', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='attendance.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='attendance__organiz_662977_idx'), models.Index(fields=['employee', 'start_date'], name='attendance__employe_cd936f_idx')],
            },
        ),
        migrations.RunPython(seed_leave_types, migrations.RunPython.noop),
    ]
