# Generated by Django 5.2.13 on 2026-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_leavetype_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allergies_or_medical_conditions',
            field=models.TextField(blank=True, help_text='Only record emergency-relevant medical information where appropriate.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_medical_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_medical_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_medical_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
