# Generated by Django 6.0.5 on 2026-06-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_employee_academic_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
