# Generated by Django 5.2.13 on 2026-06-21 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_applicant_onboardinginvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='area',
            field=models.CharField(choices=[('employee', 'Employee'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('organization', 'Organization'), ('security', 'Security'), ('admin_report', 'Admin Report')], max_length=30),
        ),
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('event', 'Event Report'), ('staff_feedback', 'Staff Feedback'), ('work_observation', 'Work Observation'), ('incident', 'Incident Report'), ('commendation', 'Commendation'), ('general', 'General Report')], default='general', max_length=30)),
                ('tone', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('concern', 'Concern'), ('urgent', 'Urgent')], default='neutral', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('body', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reports', to='attendance.organization')),
                ('related_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reports', to='attendance.department')),
                ('related_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reports', to='attendance.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='attendance__organiz_b86212_idx'), models.Index(fields=['organization', 'report_type'], name='attendance__organiz_3d0ebf_idx'), models.Index(fields=['event_date'], name='attendance__event_d_87461e_idx')],
            },
        ),
    ]
