# Generated by Django 5.2.13 on 2026-06-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_auditlog_area_adminreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_approval_status',
            field=models.CharField(choices=[('pending', 'Pending Manager Review'), ('approved', 'Manager Approved'), ('rejected', 'Manager Rejected'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
    ]
