# Generated by Django 5.2.13 on 2026-06-21 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_leaverequest_manager_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class, e.g. primary, warning, info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_stages', to='attendance.organization')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('applicant', 'Applicant'), ('employee', 'Employee')], max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_participant', to='attendance.applicant')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_participant', to='attendance.employee')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='attendance.onboardinginvitation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_participants', to='attendance.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='attendance.onboardingstage')),
            ],
            options={
                'ordering': ['stage__order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='attendance.onboardingstage'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['stage', 'status'], name='attendance__stage_i_643f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstage',
            index=models.Index(fields=['organization', 'is_active'], name='attendance__organiz_d5276f_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstage',
            index=models.Index(fields=['organization', 'order'], name='attendance__organiz_2f1393_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingstage',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='onboardingparticipant',
            index=models.Index(fields=['organization', 'status'], name='attendance__organiz_05c569_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingparticipant',
            index=models.Index(fields=['stage', 'status'], name='attendance__stage_i_5bc681_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingparticipant',
            index=models.Index(fields=['participant_type'], name='attendance__partici_b125f8_idx'),
        ),
    ]
